rtf/rtf/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin


urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'rtf.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^rtfapp/', include('rtfapp.urls', namespace="rtfapp")),
    url(r'^', include('rtfapp.urls'))
)

rtf/rtfapp/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login/', auth_views.login, {'template_name': 'rtfapp/login.html'}, name='login'),
    #To appease builtin views (for now)
    url(r'^accounts/login', auth_views.login, {'template_name': 'rtfapp/login.html'}, name='alt_login'),
    url(r'^logout/', auth_views.logout, {'template_name': 'rtfapp/index.html'}, name='logout'),
    url(r'^register/$', views.register, name='register'),
    url(r'^password_change/$', auth_views.password_change, {'post_change_redirect': '/administration/'}, name='password_change'),
    url(r'^password_change/done/$', auth_views.password_change_done, name='password_change_done'),
    url(r'^password_reset/$', auth_views.password_reset,  name='password_reset'),
    url(r'^password_reset_confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^password_reset_done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^password_reset_complete/$', auth_views.password_reset_complete, name='password_reset_complete'),
    url(r'^edit-profile/$', views.edit_profile, name='edit_profile'),
    url(r'^administration/$', views.administration, name='administration'),
    url(r'^downloadKMZ/$', views.downloadKMZ, name='downloadKMZ'),
    url(r'^downloadDB/$', views.downloadDB, name='downloadDB'),
    url(r'^uploadDB/$', views.uploadDB, name='uploadDB'),
    url(r'^maintenance-requests/$', views.maintenance_requests, name='maintenance_requests'),
    url(r'^placemarks/$', views.placemarks, name='placemarks '),
    url(r'^maintenance-requests/(?P<pk>\d+)/$', views.maintenance_requests, name='maintenance_requests'),
    url(r'^submit_request/$', views.submit_request, name='submit_request'),
    url(r'^queue-intersection/$', views.queue_intersection, name='queue_intersection'),
    url(r'^parcels/$', views.parcels, name='parcels'),
    url(r'^parcels/statuses/$', views.parcel_statuses, name='parcel_statuses'),
    url(r'^parcels/statuses/(?P<pk>\d+)/$', views.parcel_statuses, name='parcel_statuses_pk')
]

rtf/rtfapp/models.py
from django.db import models
from django.contrib.auth.models import User



class TrailSegment(models.Model):
	""" Trail Segment including line segments on trail """
	STATUS_CHOICES = [
		('Open', 'Open'),
		('Closed', 'Closed')
	]

	description = models.TextField()
	difficulty = models.IntegerField(default=0)
	name = models.TextField()
	last_edit = models.DateTimeField(auto_now_add=True)
	trail_status = models.CharField(choices=STATUS_CHOICES, default='Open', max_length=10)
	current_conditions = models.TextField()
	style_url = models.TextField()

class MaintenanceRequest(models.Model):
	""" Maintenance Request """
	description = models.TextField()
	submit_timestamp = models.DateTimeField(auto_now_add=True)
	resolved_timestamp = models.DateTimeField(blank=True, null=True)
	resolved = models.BooleanField(default=False)
	# optional One-to-one relationship with User
	# head_user = models.OneToOneField(User, unique=False, blank=True, null=True)
	created_by = models.TextField()
	# optional Many-to-many relationship with TrailSegment
	location = models.TextField()

class ParcelStatus(models.Model):
    """ Parcel status with coloration and label """
    label = models.CharField(max_length=255)
    color = models.CharField(max_length=7) # hex value

    def to_json(self):
    	return {
    		'label': self.label,
    		'color': self.color,
    		'id': self.id
    	}


def get_default_status():
	""" get default status for parcels """
	try: 
		status = ParcelStatus.objects.get(id=1)
	except DoesNotExist:
		status = ParcelStatus(label="Uncategorized", color="#00aaee")
	return status


# todo: add agreement status (will color on map) and ADDRESS
class Parcel(models.Model):
	""" Parcel for legal documentation """
	# Property identified - from city/county data
	pid = models.CharField(max_length=16)
	# Size of parcel, needs more specific unit like sq. meters
	size = models.DecimalField(max_digits=10, decimal_places=5, default=0.0)
	# Who owns the property
	owner = models.TextField()
	# Style: "lat,long lat,long ..."
	points_string = models.TextField()
	# Usually a city or a county
	parcel_type = models.CharField(max_length=255)
	# Legal status of the parcel (used on front end of the map to filter properties)
	# status = models.CharField(max_length=255, default=None)
	# Address of parcel
	address = models.TextField(default=None)
	# Whether or not the parcel is crossed by the trail
	on_trail = models.BooleanField(default=False)
	# distance to nearest trail segment
	distance_to_trail = models.FloatField()
	# Link to permissions documents on Google Drive
	permissions = models.CharField(max_length=255, default=None)
	# Miscellaneous Notes
	notes = models.CharField(max_length=255, default=None)
	status = models.ForeignKey(ParcelStatus, default=get_default_status)
	# color for parcel, overwrites status.color
	color = models.CharField(max_length=7, default='', blank=True)

class Atom(models.Model):
	""" Atoms: contained line segments that compose trail segments """
	# Style: "lat,long lat,long ..."
	coordinates = models.TextField()
	# Many-to-one relationship with Parcel
	parcel = models.ForeignKey(Parcel, blank=True, null=True)
	# Many-to-one relationship with TrailSegment
	trail_segment = models.ForeignKey(TrailSegment)
	last_edit = models.DateTimeField(auto_now_add=True)
	# Segment and position within Trail Segment that this atom belong to
	segment_id = models.IntegerField()
	position_id = models.IntegerField()

class Permission(models.Model):
	""" Permission documents for a given parcel"""
	parcel = models.ForeignKey(Parcel)
	last_edit = models.DateTimeField(auto_now_add=True)
	expiration_date = models.DateTimeField()
	path_to_doc = models.TextField()
	summary = models.TextField()

class UserProfile(models.Model):
	""" Additional information to store with a user """
	user = models.OneToOneField(User, primary_key=True)
	phone_number = models.CharField(max_length=15)
	email = models.CharField(max_length=255, blank=True, null =True)
	password_hash = models.CharField(max_length=512, blank=True, null=True)
	forgot_password_hash = models.CharField(max_length=512, blank=True, null=True)

class IntersectionTask(models.Model):
	""" Stored progress for a trail-parcel intersection task """
	started = models.DateTimeField(auto_now_add=True)
	finished = models.DateTimeField(blank=True, null=True)
	placemarks = models.IntegerField()
	placemarks_completed = models.IntegerField()
	placemark_avg_time = models.DurationField(null=True)
	parcels_extracted = models.BooleanField(default=False)

rtf/rtfapp/forms.py
from django import forms
from .models import User, UserProfile, TrailSegment

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')

class UserEditForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ('username', 'email')

class UserProfileForm(forms.ModelForm):

    class Meta:
        model = UserProfile
        fields = ('phone_number',)

class TrailAnnotationForm(forms.ModelForm):

    class Meta: 
        model = TrailSegment
        fields = ('name', 'description', 'difficulty', 'trail_status', 'current_conditions')

rtf/rtfapp/views.py
from django.shortcuts import render, render_to_response, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.template import RequestContext
from django.db.models import Q


from .models import User, UserProfile, TrailSegment, Atom, IntersectionTask
from .forms import UserForm, UserEditForm, UserProfileForm, TrailAnnotationForm
from .tasks import intersect_task

from .models import User, UserProfile, TrailSegment, Parcel, ParcelStatus

from django.core.exceptions import ObjectDoesNotExist
from django.core.servers.basehttp import FileWrapper
from django.core import serializers
from .managers import FileSystemManager, KMZManager, SHPManager, DBManager, LocationObjects
import time, datetime, os, mimetypes, csv, json, re, djqscsv

from django.http import StreamingHttpResponse, HttpResponseRedirect, HttpResponse, HttpResponseForbidden

from rtfapp.models import get_default_status

# Timestamp (month-day-year_hour-minutes-seconds)
timestamp_format = "%m-%d-%Y_%H-%M-%S"


def index(request):
	if request.user.is_authenticated():
		response = administration(request)
		return HttpResponseRedirect("administration/")
	else:
		return render(request, 'rtfapp/index.html')

def submit_request(request):
	return render(request, 'rtfapp/submit_request.html')

@login_required
def administration(request):  
  templateFile = 'rtfapp/administration.html'
  context = RequestContext(request)
  parcels = json.dumps(serialize_parcels(Parcel.objects.filter(on_trail=True)))
  return render_to_response(templateFile, {'parcels': parcels}, context)

  
@login_required
def register(request):
	'''Register a new user'''
	context = RequestContext(request)
	errors = ""
	if request.method == 'POST':
		user_form = UserForm(data=request.POST)
		user_profile_form = UserProfileForm(data=request.POST)
		if user_form.is_valid() and user_profile_form.is_valid():
			newuser = user_form.save()
			DBManager.create_new_user(newuser)
			newuser_profile = user_profile_form.save(commit=False)
			DBManager.create_new_user_profile(newuser_profile, newuser)
			return render_to_response('rtfapp/administration.html', {'name': newuser.username}, context)

		else:
			errors = user_form.errors
			prof_form_errors = user_profile_form.errors
			return render_to_response('rtfapp/register.html', {'user_form': user_form, 'user_profile_form': user_profile_form,
													   'errors': errors, 'up_form_errors': prof_form_errors}, context)
	else:
		#get
		user_form = UserForm()
		user_profile_form = UserProfileForm()
	return render_to_response('rtfapp/register.html', {'user_form': user_form, 'user_profile_form': user_profile_form,
													   }, context)

@login_required
def edit_profile(request):
	'''Edit this user's profile'''
	context = RequestContext(request)
	curr_user = request.user
	curr_user_profile = None
	try:
		curr_user_profile = UserProfile.objects.get(user=curr_user.id)
	except ObjectDoesNotExist:
		#create profile on the fly
		newuser_profile = UserProfile()
		newuser_profile.user = request.user
		newuser_profile.email = request.user.email
		newuser_profile.password_hash = request.user.password
		newuser_profile.save()
		curr_user_profile = newuser_profile
	if request.method == 'POST':
		user_edit_form = UserEditForm(data=request.POST, instance=curr_user)
		user_profile_edit_form = UserProfileForm(data=request.POST, instance=curr_user_profile)
		if user_edit_form.is_valid() and user_profile_edit_form.is_valid():
			#I feel very dirty doing this this way, but as far as I can tell there isn't an easier/better way?
			new_username = request.POST.get("username")
			if new_username != curr_user.username:
				curr_user.username = new_username
			phone_number = request.POST.get("phone_number")
			if phone_number != curr_user_profile.phone_number:
				curr_user_profile.phone_number = phone_number
			new_email = request.POST.get("email")
			if curr_user.email != new_email:
				curr_user.email = new_email
				curr_user_profile.email = new_email
			curr_user.save()
			curr_user_profile.save()
		return render_to_response('rtfapp/administration.html', {'edit_name': curr_user.username}, context)



	else:
		user_edit_form = UserEditForm(instance=curr_user)
		user_profile_edit_form = UserProfileForm(instance=curr_user_profile)
	return render_to_response('rtfapp/edit_profile.html', {'user_form': user_edit_form, 'user_profile_form': user_profile_edit_form}, context)


def downloadKMZ(request):
	""" Download the KMZ file with database content """
	kmzDir = FileSystemManager.fromHomeDir("kmz/")

	# Retrieve kmzFiles
	kmzFilePath = FileSystemManager.findLatestFile(kmzDir, ".kmz", timestamp_format)

	# Check for errors in file paths
	errors = []

	if kmzFilePath is None:
		errors.append("Unable to retrieve KMZ file, this must be uploaded")

	# Don't proceed if there are errors
	if errors:
		return HttpResponse(json.dumps({"errors": errors}))

	# Extract KML files, which saves to server file system
	kmlFiles = KMZManager.extractKMLFiles(kmzFilePath, kmzDir)
	kmlDoc = KMZManager.constructKMLFromPlacemarks(DBManager.retrievePlacemarkData(), kmlFiles[0])

	# Save file and zip
	outputDir = FileSystemManager.fromHomeDir("kmz-downloads/")
	kmlFile = FileSystemManager.fromDir(outputDir, "doc.kml")
	kmzFile = "rivanna_trail.kmz"
	kmzFilePath = FileSystemManager.fromDir(outputDir, kmzFile)

	FileSystemManager.saveFile(kmlFile, kmlDoc.to_string(prettyprint=True).encode("utf8"), overwrite=True)
	FileSystemManager.zip([kmlFile], kmzFile, output_dir=outputDir, overwrite=True)

	chunk_size = 8192
	response = StreamingHttpResponse(FileWrapper(open(kmzFilePath), chunk_size),
			content_type=mimetypes.guess_type(kmzFilePath)[0])
	response["Content-Length"] = os.path.getsize(kmzFilePath)
	response["Content-Disposition"] = 'attachment; filename=%s' % kmzFile
	return response

@login_required
def downloadDB(request):
	""" Download database contents as a zipped folder of CSVs
	"""
	#magically get a list of all models
	models = DBManager.get_model_list()
	home_dir = FileSystemManager.getHomeDir()
	file_list = []

	for model in models:
		if model._meta.verbose_name == "intersection task":
			#it doesn't make sense to dump these
			continue
		#get all objects for this model
		queryset = DBManager.dump_model(model)
		#write 1 csv per model, temporarily to homedir
		with open(home_dir + "/" + model._meta.verbose_name+".csv", "wb") as file:
			djqscsv.write_csv(queryset, file, use_verbose_names=False)
			file_list.append(file.name)
			file.close()

	#make sure there isn't an old copy of this file laying around
	if os.path.exists(home_dir + "/db.zip"):
		os.remove(home_dir + "/db.zip")

	#create zip
	FileSystemManager.zip(file_list, "db.zip")

	#wrap up and respond
	with open(home_dir +"/db.zip") as file:
		wrapper = FileWrapper(file)
		response = HttpResponse(wrapper)
		response['Content-Type'] = "application/zip"
		response['Content-Disposition'] = 'attachment; filename=db.zip'
		#clean up
		for file in file_list:
			os.remove(file)
		return response

def uploadDB(request):
	templateFile = 'rtfapp/uploadDBfromCSV.html'

	# Check for form submission
	if request.method == "POST" and "dbFile" in request.FILES:
		#Save zip file to home
		dbFile = request.FILES["dbFile"]
		dbFilePath = FileSystemManager.fromHomeDir("db.zip")
		FileSystemManager.saveFile(dbFilePath,
			dbFile.read(), overwrite=True)
		#unzip
		home = FileSystemManager.getHomeDir()
		file_list = FileSystemManager.unzip(dbFilePath)
		model_list = DBManager.get_model_list()
		#clean up file list (remove paths/extensions)
		csv_list = []
		for file in file_list:
			csv_list.append(file.split("/")[-1])
		#csv_list is a list of the names of every csv file in the zip
		#they should match the model's verbose name
		for csvf in csv_list:
			model_name = csvf.split(".")[0]
			for model in model_list:
				#go through every csv, match to an rtf_app model (NOT auth models)
				if model_name == model._meta.verbose_name:
					with open(home+"/"+csvf, 'r') as currfile:
						my_reader = csv.DictReader(currfile)
						for row in my_reader:
							newobj = model()
							for field in my_reader.fieldnames:
								for key in row.keys():
									#kludge for the fact that djqscsv writes as unicode, screwing up key-values
									#as far as the csv module is concerned
									if '\ufeff' in key:
										new_key = key.lstrip('\ufeff')
										field = new_key
										row[new_key] = row.pop(key)
									if '\xbf' in key:
										new_key = key.replace('\xef\xbb\xbf', '')
										field = new_key
										row[new_key] = row.pop(key)
								#may clean this up later
								setattr(newobj, field, row[field])
							newobj.save()
		return HttpResponse("Database upload successful<br><a href=\"/administration\">Return home </a>")

		# Default to form for upload
	return render(request, templateFile, {})

def maintenance_requests(request, pk=None):
	""" RESTful access to maintenance requests """
	if request.method == "POST" and (pk is None):
		if(all(x in request.POST for x in ['description', 'user', 'latitude', 'longitude'])):
			location = LocationObjects.formatCoordinateString([(float(request.POST['latitude']), float(request.POST['longitude']))])
			success = DBManager.create_maintenance_request(request.POST['description'], location, request.POST['user'])
		else:
			success = False
		data = json.dumps({"success": success})
		return HttpResponse(data, content_type="application/json")
	elif request.method == "GET":
		allowable_filters = {'description':'text', 'location':'text', 'created_by':'text', 'resolved':'boolean'}
		filters = {}
		for f in request.GET:
			if f in allowable_filters:
				filters[f] = convertUnicodeBoolean(request.GET[f]) if allowable_filters[f] == 'boolean' else request.GET[f]
		mrequests = DBManager.get_maintenance_requests(request_filters=filters)	
		data = serializers.serialize('json', mrequests)
		return HttpResponse(data, content_type="application/json")
	elif request.method == "POST" and pk:

rtf/rtfapp/templates/rtfapp/annotateTrails.html
<!-- temp file for implementing trail annotations -->
<!-- merge with main dashboard (click to select lines) -->

<!DOCTYPE html>
<html>
<head><title>Annotate Trails</title></head>
<body>
	{% if trails %}
	<!-- <select name="trail_id"> -->
	<ul>
		{% for trail in trails %}
<!-- 		<option value="{{ trail.id }}">{{ trail.name }}</option> -->
		<li><a href="{% url 'rtfapp:edit_trail' trail.id %}">{{trail.name}}</a></li>
		{% endfor %}
	</ul>
<!-- 	</select>
	</form> -->
	{% else %}
	<h2>No Trails Found</h2>
	{% endif %}
</body>
<html>

rtf/rtfapp/templates/rtfapp/edit_profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Edit User | Rivanna Trails Foundation</title>
</head>
<body>
    {% if errors %}
    {{ errors }}
    {% endif %}
    <form id="user_form" method="post" action="{% url 'edit_profile' %}" enctype="multipart/form-data">
    {% csrf_token %}
    {{ user_form.as_p }}
    {{ user_profile_form.as_p }}
        <input type="submit" name="submit" value="Save" />
    </form>
</body>
</html>

rtf/rtfapp/templates/rtfapp/edit_trail.html
<h1>{{trail.name}}</h1>
<form action="{% url 'rtfapp:edit_trail' trail.id %}" method="POST">
	{% csrf_token %}
	{% for field in form.visible_fields %}
	{{ field.errors }} <br>
	{{ field.label_tag }}<br>
	{{ field }}<br>
	{% endfor %}

	<input type="submit" value="Submit"/>
</form>

rtf/rtfapp/templates/rtfapp/header.html
<!DOCTYPE html>

{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'rtfapp/header.css' %}" />
<div class=".rtf__header_box"/>
</div>

rtf/rtfapp/templates/rtfapp/logged_out.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Logged Out | Rivanna Trails Foundation</title>
</head>
<body>
    You have been logged out. <a href="{% url 'index' %}">Click here</a> to return home.
</body>
</html>

rtf/rtfapp/templates/rtfapp/login.html
<!DOCTYPE html>

{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'rtfapp/shared.css' %}" />


<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login | Rivanna Trails Foundation</title>
</head>
<body class="rtf__landing_body rtf__centered_text">
    <div class ="rtf__landing_box">
        <div class="rtf__landing_content">
            {% if form.errors %}
            <p class= "rtf__error_text"><b>
                Invalid username or password</b>
            </p>
            {% endif %}

            <form method="post" action="{% url 'django.contrib.auth.views.login' %}">
                {% csrf_token %}
                <table class="rtf__table_center">

                    <tr class="rtf__input_flat">
                        <td>{{ form.username.label_tag }}</td>
                        <td class="rtf__input_flat">{{ form.username }}</td>
                    </tr>
                    <tr>
                        <td>{{ form.password.label_tag }}</td>
                        <td>{{ form.password }}</td>
                    </tr>
                </table>

                <input class="rtf__button_flat rtf__button_green" type="submit" value="Login"/>
                
                <input type="hidden" name="next" value="{% url 'administration' %}" />
            </form>

            <a class="rtf__button_flat rtf__button_green" href="{% url 'password_reset' %}">
                Forgot password?
            </a>

        <div>
    <div>
</body>
</html>

rtf/rtfapp/templates/rtfapp/password_reset.html
<title>Reset Password | Rivanna Trails Foundation</title>

<p>Please specify the e-mail address associated with your account, and you will receive instructions for resetting your password.</p>

<form action="" method="post">
    <div style="display:none">
        <input type="hidden" value="{{ csrf_token }}" name="csrfmiddlewaretoken">
    </div>
     {{ form.email.errors }}
    <p><label for="id_email">E-mail address:</label> {{ form.email }} <input type="submit" value="Reset password" /></p>
</form>

rtf/rtfapp/templates/rtfapp/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Register | Rivanna Trails Foundation</title>
</head>
<body>
    {% if errors %}
        <h2>Errors</h2>
        {{ errors }}
    {% endif %}
    <form id="user_form" method="post" action="{% url 'register' %}" enctype="multipart/form-data">
    {% csrf_token %}
    {{ user_form.as_p }}
    {{ user_profile_form.as_p }}
        <input type="submit" name="submit" value="Register" />
    </form>
</body>
</html>

rtf/rtfapp/templates/rtfapp/uploadCounty.html
{% if parcels %}
	<h2>{{ parcels | length }} parcels were found!</h2>
	<ul>
		{% for parcel in parcels %}
			<li>
				Parcel {{forloop.counter}} - <br/>
				<ul>
				
					<li>Parcel ID: {{parcel.id}}</li>
					<li>Owner: {{parcel.owner}}</li>
					<li>Points: {{parcel.points}}</li>
					
				</ul>
			</li>
		{% endfor %}
	</ul>
{% else %}
	<h2>Upload a Zipped Shapefile for land parcels</h2>

	<form action="{% url 'rtfapp:uploadCounty' %}" method="post" enctype="multipart/form-data">
		{% csrf_token %}
		<label>
			County Shp Zip:<br/>
			<input type="file" name="countyShpFiles" id="countyShpFiles" accept=".zip" />
		</label>
		<br><br>
		<label>
			County Excel Zip:<br/>
			<input type="file" name="countyExcelFiles" id="countyExcelFiles" accept=".zip" />
		</label>		
		<br><br>
		<br><br>
		<input type="submit" value="Upload" />
	</form>
{% endif %}

rtf/rtfapp/templates/rtfapp/uploadDBfromCSV.html
{% load staticfiles %}
{% if done %}
	<h2>Upload was successful!</h2>
{% else %}
<link rel="stylesheet" type="text/css" href="{% static 'rtfapp/upload.css' %}" />
	{% if errors %}
		<h4>Errors occurred preventing upload</h4>
		<ul>
		{% for error in errors %}
			<li>{{ error }}</li>
		{% endfor %}
		</ul>
	{% endif %}
<html lang="en">
	<head>
    <meta charset="UTF-8">
    <title>Restore the Database from Backup</title>
	</head>
	<div class="rtf__upload_box">
		<p class = "rtf__upload_header_text">
			Upload a Database Backup zip file
		</p>
	<form action="{% url 'rtfapp:uploadDB' %}" method="post" enctype="multipart/form-data">
		{% csrf_token %}
		<br>
		<label style="padding-left:7em">
			db.zip file:
		</label>
				<div class="fileUpload rtf__button_flat rtf__upload_button_green">
				    <span>Choose File</span>
				    <input type="file" class = "upload" name="dbFile" id="dbFile" accept=".zip" />
				</div>

		<br><br><br>
			<div style="padding-left:14.3em" />  
				<div class= "fileUpload rtf__button_flat rtf__upload_button_blue">
					<span>Upload</span>
					<input type = "submit" class = "upload" value="Upload"/>
				</div>
			</div>
	</form>
</div>
{% endif %}
</html>

rtf/rtfapp/templates/rtfapp/uploadFiles.html
{% load staticfiles %}
{% if placemarks %}
	<h2>{{ placemarks | length }} placemarks were found!</h2>
	<ul>
		{% for placemark in placemarks %}
			<li>{{ placemark.name }} <br />
				<ul>
					<li>{{ placemark.description }}</li>
					<li>Atoms ({{ placemark.atoms | length }}):
						<ul>
							{% for atom in placemark.atoms %}
								<li>Atom {{forloop.counter}}: {{atom.coordinates}}
								<ul>
									<li>Parcel: {{ atom.parcel }} </li>
								</ul>
								</li>
							{% endfor %}
						</ul>
					</li>

				</ul>
			</li>
		{% endfor %}
	</ul>
{% else %}
<link rel="stylesheet" type="text/css" href="{% static 'rtfapp/upload.css' %}" />
	{% if errors %}
		<h4>Errors occurred preventing upload</h4>
		<ul>
		{% for error in errors %}
			<li>{{ error }}</li>
		{% endfor %}
		</ul>
	{% endif %}
<html lang="en">
	<head>
    <meta charset="UTF-8">
    <title>Upload a KMZ for trail segments and Zipped Shapefile for land parcels</title>
	</head>
	<div class="rtf__upload_box">
		<p class = "rtf__upload_header_text">
			Upload a KMZ for trail segments and Zipped Shapefile for land parcels
		</p>
	
</div>
{% endif %}